export type CurrentBatteryPowerBroadcast = { time: number; value: number };
export type MqttValue = { time: number; value: number };

export const mqttValueKeys = [
  "solar_input_power_1",
  "solar_input_power_2",
  "ac_input_active_power_r",
  "ac_input_active_power_s",
  "ac_input_active_power_t",
  "ac_input_total_active_power",
  "ac_output_active_power_r",
  "ac_output_active_power_s",
  "ac_output_active_power_t",
  "ac_output_total_active_power",
  "ac_output_apparent_power_r",
  "ac_output_apparent_power_s",
  "ac_output_apparent_power_t",
  "ac_output_total_apparent_power",
  "ac_output_power_percentage",
  "ac_output_connect_status",
  "solar_input_1_work_status",
  "solar_input_2_work_status",
  "battery_power_direction",
  "dc/ac_power_direction",
  "line_power_direction",
  "solar_input_voltage_1",
  "solar_input_voltage_2",
  "solar_input_current_1",
  "solar_input_current_2",
  "battery_voltage",
  "battery_capacity",
  "battery_current",
  "ac_input_voltage_r",
  "ac_input_voltage_s",
  "ac_input_voltage_t",
  "ac_input_frequency",
  "ac_input_current_r",
  "ac_input_current_s",
  "ac_input_current_t",
  "ac_output_voltage_r",
  "ac_output_voltage_s",
  "ac_output_voltage_t",
  "ac_output_frequency",
  "inner_temperature",
  "component_max_temperature",
  "external_battery_temperature",
  "setting_change_bit",
] as const;
