name: TypeScript Check

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Specify the Node.js version here

      - name: Install dependencies
        run: yarn install

      - name: Run typecheck
        run: yarn typecheck
